-- Generated by MADS.rs. Review before applying.
-- Unsupported defaults, indexes, checks, triggers, and FK policies are not synthesized.

CREATE TABLE "public"."users" (
    "id" bigint NOT NULL,
    "email" varchar(255) NOT NULL,
    "nickname" text,
    PRIMARY KEY ("id")
);
